// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndReadFile() {
  return window['go']['main']['App']['CheckAndReadFile']();
}

export function CheckConfigFile() {
  return window['go']['main']['App']['CheckConfigFile']();
}
